name: CI/CD Pipeline for Loan Approval App

on:
  push:
    branches:
      - main  # Or your deployment branch

jobs:
  deploy:
    name: Build, DVC Push, and Deploy to GCP
    runs-on: ubuntu-latest

    env:
      REGION: ${{ secrets.GCP_REGION_NAME }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Correct Authentication step
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure GCP credentials for DVC (GCS)
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
          dvc remote modify origin credentialpath gcp-key.json

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: DVC repro
        run: |
          dvc repro

      - name: Debug DVC remote config
        run: |
         dvc remote list -v
      
      - name: DVC Push
        run: |
          dvc push

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --source . \
            --platform managed \
            --region $REGION \
            --project $PROJECT_ID \
            --set-env-vars MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }},GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }} \
            --allow-unauthenticated
